"""empty message

Revision ID: 27a475bde4f
Revises: None
Create Date: 2016-01-30 22:28:32.678260

"""

# revision identifiers, used by Alembic.
revision = '27a475bde4f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slave_hostname', sa.String(length=100), nullable=False),
    sa.Column('slave_version', sa.String(length=100), nullable=False),
    sa.Column('slave_system', sa.String(length=100), nullable=False),
    sa.Column('slave_cores', sa.Integer(), nullable=False),
    sa.Column('slave_distribution', sa.String(length=100), nullable=False),
    sa.Column('slave_ip', sa.String(length=100), nullable=False),
    sa.Column('slave_last_connect', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testrole_id', sa.Integer(), nullable=False),
    sa.Column('testhistory_result', sa.Integer(), nullable=True),
    sa.Column('testhistory_datime', sa.DateTime(), nullable=True),
    sa.Column('testhistory_log', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('testrole_name', sa.String(length=100), nullable=True),
    sa.Column('testrole_status', sa.Integer(), nullable=True),
    sa.Column('testrole_start_time', sa.DateTime(), nullable=True),
    sa.Column('testrole_end_time', sa.DateTime(), nullable=True),
    sa.Column('testrole_log', sa.String(), nullable=True),
    sa.Column('slave_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_pushedat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.drop_table('testroles')
    op.drop_table('testhistory')
    op.drop_table('slaves')
    ### end Alembic commands ###
