"""empty message

Revision ID: 2d7d656ecc4
Revises: None
Create Date: 2016-01-30 20:14:36.098823

"""

# revision identifiers, used by Alembic.
revision = '2d7d656ecc4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slave_hostname', sa.String(length=100), nullable=False),
    sa.Column('slave_version', sa.String(length=100), nullable=False),
    sa.Column('slave_system', sa.String(length=100), nullable=False),
    sa.Column('slave_cores', sa.String(length=100), nullable=False),
    sa.Column('slave_distribution', sa.String(length=100), nullable=False),
    sa.Column('slave_ip', sa.String(length=100), nullable=False),
    sa.Column('slave_last_connect', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testrole_id', sa.Integer(), nullable=False),
    sa.Column('testhistory_result', sa.Integer(), nullable=True),
    sa.Column('testhistory_datime', sa.DateTime(), nullable=True),
    sa.Column('testhistory_log', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testrole_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testroles')
    op.drop_table('testhistory')
    op.drop_table('slaves')
    ### end Alembic commands ###
